"""Generate policy/opa/access.rego from semantic-layer/access-semantics.yaml (ADR-0005, F-21).

Usage: python scripts/generate_rego.py [--check]   (--check exits 1 if the committed file differs)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from apps.api.config import _semantic_dir  # noqa: E402
from apps.api.security.policy import PolicyEngine  # noqa: E402

OUT = ROOT / "policy" / "opa" / "access.rego"

TEMPLATE = """# GENERATED by scripts/generate_rego.py from semantic-layer/access-semantics.yaml. Do not edit by hand.
# Deny by default. Input: {{"persona": str, "entity": str, "action": "read"|"write", "purpose": str}}
package logistics.access

import rego.v1

default allow := false

levels := {{"none": 0, "read": 1, "write": 2}}

matrix := {matrix}

allow if {{
	entry := matrix[input.persona][input.entity]
	levels[entry.access] >= levels[input.action]
	input.purpose in entry.purposes
}}

deny_reason := "persona or entity not declared" if {{
	not matrix[input.persona][input.entity]
}}
"""


def render() -> str:
    eng = PolicyEngine.from_dir(_semantic_dir())
    return TEMPLATE.format(matrix=json.dumps(eng.matrix(), indent=2, sort_keys=True))


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        return 0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1
    OUT.write_text(text, encoding="utf-8")
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
