# (criterion, sub-dimension, status, reason)  status in MET / PARTIAL / NOT MET / BLOCKED
ROWS=[
("R1","Understanding Repo 1.0","MET","13 discovery artifacts (runbook said 12), current-state set and repo assessment, built from code, data, configuration and tests. Caveat: root cause RC-1 (who owns the partial modernisation) was not confirmed by an owner interview."),
("R1","Identifying gaps and inconsistencies","MET","62 findings (runbook said 57; five found after Stage A); declared-versus-implemented gaps named (F-05 portal, F-29 AI, F-50 contract); data profile and flow-to-code trace present."),
("R1","Technical debt","MET","`technical-debt-register.md` now cross-references all 62 finding IDs (it covered 60; F-61 and F-62 were added in this run, step 03-1)."),
("R1","Risk identification","MET","`initial-risk-register.md` and `evidence-confidence-matrix.md` carry supporting evidence, contradicting evidence and a confidence level per cause."),
("R1","Behavioural baseline","MET","Documented quick-start recorded failing on the as-delivered tag (EVD-C-02); 12 characterization tests pin 11 behaviours (5 stay green, 7 xfail by approved change)."),
("R1","Business problem","MET","`problem-statement.md` is technology-neutral (0 mentions of AI, LLM or model, checked by search in this run)."),
("R1","Before/after proof","PARTIAL","Behaviour diff classified with 0 unexplained and one business event reconstructed end to end (EVD-N-02). No business KPI moved: the variance table holds proxies only and states no benefit was measured (B-5, B-6)."),
("R2","Improved architecture","MET","Options compared (`architecture-options.md`); ADR-0002..0010 (the original ADR-0001 is in the app subtree and ADR-0002 supersedes it)."),
("R2","AI workflow","MET","Prompt registry with locked hashes, deterministic boundary, suggest-only output with approval record; red-team RT-10 (action without approval) fails. Quality of a real model is unmeasured (B-1)."),
("R2","Data / evidence design","MET","Semantic layer validates against its schema, generates its JSON and has 16 tests; data contracts, quality rules and provenance policy exist."),
("R2","Decisioning","PARTIAL","Role, entity, field and purpose are enforced, with Rego generated from `access-semantics.yaml`. Scope narrowing is reported but not enforced (declared gap, `scope_enforced=false`); risk is handled through the autonomy matrix, not the access decision."),
("R2","Controls","MET","Secret scan, negative access tests, smoke test and SBOM present; the tree needs no sensitive value. The credentials remain in git history and are not revoked (B-13, 4 findings FIXED-IN-TREE)."),
("R2","Resilience","PARTIAL","Resilience architecture, AI-disabled mode and five drills pass. M-X2 NOT MET: IaC provisions nothing because no platform is chosen (OQ-01, B-4)."),
("R2","Reproducibility","PARTIAL","Quick-start succeeds after the fix, hash-locked requirements, Dockerfile. No real IaC (B-4);"),
("R2","Delivery pipeline","MET","CI on GitHub: first real run failed on the coverage gate (D-013), second run green on Python 3.11 and 3.14; the pipeline uploads artifacts. Branch protection was not enabled when last checked."),
("R2","Portability","PARTIAL","Run once on a four-behaviour subset with a same-vendor model: safety behaviour carried over, AI-output fidelity did not (2 of 8 gates fail), eight specification gaps open (IMP-Q04..Q13)."),
("R3","Human oversight","MET","Approval enforced in code (decision endpoint, 409 on a second decision, approval record); closes F-26; human-control tests pass."),
("R3","Explainability","MET","Every AI response carries model, model version, prompt version and config hash; the audit event carries an input hash. Deterministic provider only: no real-model explanation exists."),
("R3","Auditability","MET","Hash-chained audit v2 with tamper detection; one event reconstructed end to end (field coverage 10 of 10) with the before-state gap documented."),
("R3","Risk controls","NOT MET","Residual risks have role-level owners only; 0 of 12 risk acceptances are signed; no approver exists (OQ-05, B-8). The standard asks for a named owner and an acceptance record."),
("R3","Security","MET","Repeatable validation: red team 10 of 12 attacks succeed at baseline and 0 of 12 on v2, 25 security tests, bandit triaged, pip-audit 0, SBOM. Graded by the same agent that built it."),
("R3","Compliance","BLOCKED","No regulatory regime is named (OQ-04, B-3). A candidate obligations set exists, labelled an unvalidated assumption, with a validation plan and risk acceptance RA-01 (unsigned)."),
("R3","Observability","PARTIAL","SLOs, dashboards and alerts as code are validated offline; correlation flows API to data to AI to policy to approval to audit. No collector, no traces, no deployed scrape; the UI is a thin view."),
("R3","Safe AI boundaries","MET","Injection payloads seeded into the data (RT-07, RT-08) are defended; untrusted text is delimited and sanitised; 0 injection-marker leaks in 192 evaluation cases."),
("R3","Change governance","PARTIAL","CODEOWNERS and a controlled-change process exist; prompt hashes are locked by script. The authorisation record EVD-G-04 is unsigned and branch protection was not enabled when last checked, so an untracked change is not technically prevented."),
("R4","PRD quality","MET","Three distinct PRDs (initial, implementation, final as-built); the later two are reconciliations with a change log."),
("R4","Requirement traceability","MET","Finding coverage matrix (62 rows) and requirement disposition matrix (48 rows, 0 unclassified); no orphan requirement found. Dispositions have role owners but no approver."),
("R4","Functional implementation","MET","176 tests pass on the repository suite; every characterization difference is explained (0 unexplained); coverage gate 80% on apps and etl."),
("R4","End-to-end workflow","PARTIAL","A complete workflow (lookup, summary, approval, audit, reconstruction) runs against the running service and the thin view passes 10 of 10 browser checks. No recording with a person; the demo rehearsal was by the author, offline."),
("R4","Working AI capabilities","BLOCKED","No real model was ever called (B-1, OQ-02, OQ-03). The governed AI workflow runs on a deterministic provider and passes 192 of 192 evaluation cases; model quality, latency and cost are unmeasured."),
("R4","Evidence-driven delivery","MET","Definition of done and evidence checklist exist; every evidence file is in a hash manifest (134 of 134 rows verified)."),
("R5","Storytelling","MET","Executive narrative and problem-to-value story map claims to evidence (34-claim index)."),
("R5","Demo quality","PARTIAL","Demo script with 28 s of offline beats rehearsed by the author; no audience, no recording of a person, budget unconfirmed (OQ-16, OQ-17; Q-X5 partial)."),
("R5","Explaining design choices","MET","ADR set, architecture defence and AI decision defence state rejected alternatives."),
("R5","Trade-offs and limitations","MET","Known limitations, lessons learned and residual risks state failures voluntarily (R-X5 met)."),
("R5","Answering evaluator questions","MET","\"What happened to finding X?\" is one lookup in `EVD-F-04b-finding-disposition-final.csv`; the rubric-aware evidence index built in this run adds findings and criteria per file."),
]
