# GENERATED by scripts/generate_rego.py from semantic-layer/access-semantics.yaml. Do not edit by hand.
# Deny by default. Input: {"persona": str, "entity": str, "action": "read"|"write", "purpose": str}
package logistics.access

import rego.v1

default allow := false

levels := {"none": 0, "read": 1, "write": 2}

matrix := {
  "ai_agent": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "read",
      "purposes": [
        "exception_summary"
      ]
    },
    "routes": {
      "access": "read",
      "purposes": [
        "exception_summary"
      ]
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "exception_summary"
      ]
    },
    "tracking_events": {
      "access": "read",
      "purposes": [
        "exception_summary"
      ]
    },
    "vehicles": {
      "access": "none",
      "purposes": []
    }
  },
  "carrier_partner": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "write",
      "purposes": [
        "booking"
      ]
    },
    "routes": {
      "access": "none",
      "purposes": []
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "booking"
      ]
    },
    "tracking_events": {
      "access": "none",
      "purposes": []
    },
    "vehicles": {
      "access": "none",
      "purposes": []
    }
  },
  "customer_support": {
    "ai_invocations": {
      "access": "read",
      "purposes": [
        "customer_support"
      ]
    },
    "carrier_bookings": {
      "access": "read",
      "purposes": [
        "customer_support"
      ]
    },
    "routes": {
      "access": "none",
      "purposes": []
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "customer_support"
      ]
    },
    "tracking_events": {
      "access": "read",
      "purposes": [
        "customer_support"
      ]
    },
    "vehicles": {
      "access": "none",
      "purposes": []
    }
  },
  "customs_agent": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "none",
      "purposes": []
    },
    "routes": {
      "access": "none",
      "purposes": []
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "customs_clearance"
      ]
    },
    "tracking_events": {
      "access": "read",
      "purposes": [
        "customs_clearance"
      ]
    },
    "vehicles": {
      "access": "none",
      "purposes": []
    }
  },
  "dispatcher": {
    "ai_invocations": {
      "access": "read",
      "purposes": [
        "dispatch"
      ]
    },
    "carrier_bookings": {
      "access": "read",
      "purposes": [
        "dispatch"
      ]
    },
    "routes": {
      "access": "write",
      "purposes": [
        "dispatch",
        "route_planning"
      ]
    },
    "shipments": {
      "access": "write",
      "purposes": [
        "dispatch"
      ]
    },
    "tracking_events": {
      "access": "read",
      "purposes": [
        "dispatch"
      ]
    },
    "vehicles": {
      "access": "read",
      "purposes": [
        "dispatch"
      ]
    }
  },
  "driver": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "none",
      "purposes": []
    },
    "routes": {
      "access": "read",
      "purposes": [
        "delivery"
      ]
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "delivery"
      ]
    },
    "tracking_events": {
      "access": "none",
      "purposes": []
    },
    "vehicles": {
      "access": "read",
      "purposes": [
        "delivery"
      ]
    }
  },
  "fleet_manager": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "none",
      "purposes": []
    },
    "routes": {
      "access": "read",
      "purposes": [
        "fleet_management"
      ]
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "fleet_management"
      ]
    },
    "tracking_events": {
      "access": "read",
      "purposes": [
        "fleet_management"
      ]
    },
    "vehicles": {
      "access": "write",
      "purposes": [
        "fleet_management"
      ]
    }
  },
  "warehouse_ops": {
    "ai_invocations": {
      "access": "none",
      "purposes": []
    },
    "carrier_bookings": {
      "access": "none",
      "purposes": []
    },
    "routes": {
      "access": "read",
      "purposes": [
        "handling"
      ]
    },
    "shipments": {
      "access": "read",
      "purposes": [
        "handling"
      ]
    },
    "tracking_events": {
      "access": "write",
      "purposes": [
        "handling"
      ]
    },
    "vehicles": {
      "access": "read",
      "purposes": [
        "handling"
      ]
    }
  }
}

allow if {
	entry := matrix[input.persona][input.entity]
	levels[entry.access] >= levels[input.action]
	input.purpose in entry.purposes
}

deny_reason := "persona or entity not declared" if {
	not matrix[input.persona][input.entity]
}
